---
services:
  traderpilot:
    image: traderpilotorg/traderpilot:stable
    # image: traderpilotorg/traderpilot:develop
    # Use plotting image
    # image: traderpilotorg/traderpilot:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for traderAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: traderpilot
    volumes:
      - "./user_data:/traderpilot/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.traderpilot.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /traderpilot/user_data/logs/traderpilot.log
      --db-url sqlite:////traderpilot/user_data/tradesv3.sqlite
      --config /traderpilot/user_data/config.json
      --strategy SampleStrategy
