ARG sourceimage=traderpilotorg/traderpilot
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-traderai.txt /traderpilot/

RUN pip install -r requirements-traderai.txt --user --no-cache-dir
